
CREATE TABLE IF NOT EXISTS advertisements (
  id INT AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  position ENUM('left', 'right') NOT NULL,
  imageUrl TEXT,
  linkUrl TEXT,
  active BOOLEAN DEFAULT 1,
  startDate DATE NOT NULL,
  endDate DATE NOT NULL,
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
